#!/bin/sh

doas ifconfig iwn0 nwid enter-your-wifi-name-here wpakey enter-your-wifi-password-here && doas ifconfig iwn0 join enter-your-wifi-name-here wpakey enter-your-wifi-password-here && doas dhclient iwn0 
